---
- name: Check if MongoDB is installed
  command: bash -c "dpkg --get-selections | grep mongodb"
  register: mongodb_installed
  ignore_errors: True

- name: Install MongoDB
  apt: name={{item}} state=present force=yes
  when: mongodb_installed | failed
  with_items:
    - mongodb-org
    - build-essential
    - git
    - openssl
    - libssl-dev
    - pkg-config
